/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotfoundRouteImport } from './routes/notfound'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ResetTokenRouteImport } from './routes/reset/$token'
import { Route as ProjectsExploreRouteImport } from './routes/projects/explore'
import { Route as ProjectsCreateRouteImport } from './routes/projects/create'
import { Route as ProjectsProjectIDRouteImport } from './routes/projects/$projectID'
import { Route as DeactivateTokenRouteImport } from './routes/deactivate/$token'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as ActivateTokenRouteImport } from './routes/activate/$token'
import { Route as ProjectsUserUserIDRouteImport } from './routes/projects/user/$userID'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotfoundRoute = NotfoundRouteImport.update({
  id: '/notfound',
  path: '/notfound',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetTokenRoute = ResetTokenRouteImport.update({
  id: '/reset/$token',
  path: '/reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsExploreRoute = ProjectsExploreRouteImport.update({
  id: '/projects/explore',
  path: '/projects/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIDRoute = ProjectsProjectIDRouteImport.update({
  id: '/projects/$projectID',
  path: '/projects/$projectID',
  getParentRoute: () => rootRouteImport,
} as any)
const DeactivateTokenRoute = DeactivateTokenRouteImport.update({
  id: '/deactivate/$token',
  path: '/deactivate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateTokenRoute = ActivateTokenRouteImport.update({
  id: '/activate/$token',
  path: '/activate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsUserUserIDRoute = ProjectsUserUserIDRouteImport.update({
  id: '/projects/user/$userID',
  path: '/projects/user/$userID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notfound': typeof NotfoundRoute
  '/register': typeof RegisterRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/deactivate/$token': typeof DeactivateTokenRoute
  '/projects/$projectID': typeof ProjectsProjectIDRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/explore': typeof ProjectsExploreRoute
  '/reset/$token': typeof ResetTokenRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/user/$userID': typeof ProjectsUserUserIDRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notfound': typeof NotfoundRoute
  '/register': typeof RegisterRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/deactivate/$token': typeof DeactivateTokenRoute
  '/projects/$projectID': typeof ProjectsProjectIDRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/explore': typeof ProjectsExploreRoute
  '/reset/$token': typeof ResetTokenRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/user/$userID': typeof ProjectsUserUserIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notfound': typeof NotfoundRoute
  '/register': typeof RegisterRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/deactivate/$token': typeof DeactivateTokenRoute
  '/projects/$projectID': typeof ProjectsProjectIDRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/explore': typeof ProjectsExploreRoute
  '/reset/$token': typeof ResetTokenRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/user/$userID': typeof ProjectsUserUserIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notfound'
    | '/register'
    | '/activate/$token'
    | '/admin/projects'
    | '/admin/users'
    | '/deactivate/$token'
    | '/projects/$projectID'
    | '/projects/create'
    | '/projects/explore'
    | '/reset/$token'
    | '/projects'
    | '/projects/user/$userID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notfound'
    | '/register'
    | '/activate/$token'
    | '/admin/projects'
    | '/admin/users'
    | '/deactivate/$token'
    | '/projects/$projectID'
    | '/projects/create'
    | '/projects/explore'
    | '/reset/$token'
    | '/projects'
    | '/projects/user/$userID'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notfound'
    | '/register'
    | '/activate/$token'
    | '/admin/projects'
    | '/admin/users'
    | '/deactivate/$token'
    | '/projects/$projectID'
    | '/projects/create'
    | '/projects/explore'
    | '/reset/$token'
    | '/projects/'
    | '/projects/user/$userID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotfoundRoute: typeof NotfoundRoute
  RegisterRoute: typeof RegisterRoute
  ActivateTokenRoute: typeof ActivateTokenRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DeactivateTokenRoute: typeof DeactivateTokenRoute
  ProjectsProjectIDRoute: typeof ProjectsProjectIDRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  ProjectsExploreRoute: typeof ProjectsExploreRoute
  ResetTokenRoute: typeof ResetTokenRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsUserUserIDRoute: typeof ProjectsUserUserIDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notfound': {
      id: '/notfound'
      path: '/notfound'
      fullPath: '/notfound'
      preLoaderRoute: typeof NotfoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset/$token': {
      id: '/reset/$token'
      path: '/reset/$token'
      fullPath: '/reset/$token'
      preLoaderRoute: typeof ResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/explore': {
      id: '/projects/explore'
      path: '/projects/explore'
      fullPath: '/projects/explore'
      preLoaderRoute: typeof ProjectsExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectID': {
      id: '/projects/$projectID'
      path: '/projects/$projectID'
      fullPath: '/projects/$projectID'
      preLoaderRoute: typeof ProjectsProjectIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deactivate/$token': {
      id: '/deactivate/$token'
      path: '/deactivate/$token'
      fullPath: '/deactivate/$token'
      preLoaderRoute: typeof DeactivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/$token': {
      id: '/activate/$token'
      path: '/activate/$token'
      fullPath: '/activate/$token'
      preLoaderRoute: typeof ActivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/user/$userID': {
      id: '/projects/user/$userID'
      path: '/projects/user/$userID'
      fullPath: '/projects/user/$userID'
      preLoaderRoute: typeof ProjectsUserUserIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotfoundRoute: NotfoundRoute,
  RegisterRoute: RegisterRoute,
  ActivateTokenRoute: ActivateTokenRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DeactivateTokenRoute: DeactivateTokenRoute,
  ProjectsProjectIDRoute: ProjectsProjectIDRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  ProjectsExploreRoute: ProjectsExploreRoute,
  ResetTokenRoute: ResetTokenRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsUserUserIDRoute: ProjectsUserUserIDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
